mkdir _puzzle
cp aquarush.zip _puzzle
cp bakubaku.zip _puzzle
cp bangball.zip _puzzle
cp blockhl.zip _puzzle
cp blockout.zip _puzzle
cp cshift.zip _puzzle
cp columns.zip _puzzle
cp crospang.zip _puzzle
cp dharma.zip _puzzle
cp deroon.zip _puzzle
cp drmario.zip _puzzle
cp emeralda.zip _puzzle
cp namcoc70.zip _puzzle
cp plotting.zip _puzzle
cp ghostlop.zip _puzzle
cp neogeo.zip _puzzle
cp htchctch.zip _puzzle
cp joyjoy.zip _puzzle
cp klax.zip _puzzle
cp landmakr.zip _puzzle
cp locomotn.zip _puzzle
cp magerror.zip _puzzle
cp stvbios.zip _puzzle
cp mosaicf2.zip _puzzle
cp msgogo.zip _puzzle
cp mrdrillr.zip _puzzle
cp magdrop3.zip _puzzle
cp motos.zip _puzzle
cp miexchng.zip _puzzle
cp ohmygod.zip _puzzle
cp spang.zip  _puzzle
cp taitogn.zip _puzzle
cp pururun.zip _puzzle
cp puyopuy2.zip _puzzle
cp puzzloop.zip _puzzle
cp skns.zip _puzzle
cp pzloop2.zip _puzzle
cp puzzledp.zip _puzzle
cp pbobble2.zip _puzzle
cp pbobble4.zip _puzzle
cp mushitam.zip _puzzle
cp puzzli2s.zip _puzzle
cp puzzli2.zip _puzzle
cp qix.zip _puzzle
cp riskchal.zip _puzzle
cp senkyu.zip _puzzle
cp ar_spot.zip _puzzle
cp ar_bios.zip _puzzle
cp spf2t.zip _puzzle
cp qsound.zip _puzzle
cp tokkae.zip _puzzle
cp konamigx.zip _puzzle
cp tetrisp2.zip _puzzle
cp tgm2.zip _puzzle
cp uopoko.zip _puzzle
cp watrball.zip _puzzle