#!/bin/bash

mkdir _horshmups
cp sonicwi2.zip _horshmups
cp airbustr.zip _horshmups
cp alpham2.zip _horshmups
cp androdun.zip _horshmups
cp bchopper.zip _horshmups
cp blkheart.zip _horshmups
cp blazeon.zip _horshmups
cp blazstar.zip _horshmups
cp boogwing.zip _horshmups
cp bosco.zip _horshmups
cp namco50.zip _horshmups
cp namco51.zip _horshmups
cp namco52.zip _horshmups
cp namco54.zip _horshmups
cp cawing.zip _horshmups
cp choplift.zip _horshmups
cp chukatai.zip _horshmups
cp cobracom.zip _horshmups
cp cotton.zip _horshmups
cp cotton2.zip _horshmups
cp cottonbm.zip _horshmups
cp darius.zip _horshmups
cp dariusg.zip _horshmups
cp darius2.zip _horshmups
cp darius2d.zip _horshmups
cp deathsml.zip _horshmups
cp dbreed.zip _horshmups
cp edf.zip _horshmups
cp ecofghtr.zip _horshmups
cp qsound.zip _horshmups
cp taitofx1.zip _horshmups
cp fantjour.zip _horshmups
cp gdarius.zip _horshmups
cp gdarius2.zip _horshmups
cp gforce2.zip _horshmups
cp gigawing.zip _horshmups
cp nemesis.zip _horshmups
cp gradius.zip _horshmups
cp gradius4.zip _horshmups
cp gradius3.zip _horshmups
cp gratia.zip _horshmups
cp hellfire.zip _horshmups
cp hyprduel.zip _horshmups
cp inthunt.zip _horshmups
cp junofrst.zip _horshmups
cp strahl.zip _horshmups
cp lresort.zip _horshmups
cp neogeo.zip _horshmups
cp mmatrix.zip _horshmups
cp metalb.zip _horshmups
cp mysticri.zip _horshmups
cp ordyne.zip _horshmups
cp p47.zip _horshmups
cp p47aces.zip _horshmups
cp parodius.zip _horshmups
cp prehisle.zip _horshmups
cp progear.zip _horshmups
cp pulstar.zip _horshmups
cp rtype.zip _horshmups
cp rtype2.zip _horshmups
cp rtypeleo.zip _horshmups
cp rsgun.zip _horshmups
cp stvbios.zip _horshmups
cp stratof.zip _horshmups
cp raystorm.zip _horshmups
cp taitofx1.zip _horshmups
cp rohga.zip _horshmups
cp stdragon.zip _horshmups
cp salamand.zip _horshmups
cp salmndr2.zip _horshmups
cp konamigx.zip _horshmups
cp sexyparo.zip _horshmups
cp sidearms.zip _horshmups
cp soldivid.zip _horshmups
cp sokyugrt.zip _horshmups
cp macross2.zip _horshmups
cp tengai.zip _horshmups
cp terraf.zip _horshmups
cp thunderx.zip _horshmups
cp thndrx2.zip _horshmups
cp tbyahhoo.zip _horshmups
cp twinspri.zip _horshmups
cp unsquad.zip _horshmups
cp xmultipl.zip _horshmups
cp xevi3dg.zip _horshmups
cp namcoc76.zip _horshmups
cp xexex.zip _horshmups
cp xexexj.zip _horshmups
cp zerowing.zip _horshmups



mkdir _vertshmups
cp 1942.zip _vertshmups
cp 1943.zip _vertshmups
cp vspsx.zip _vertshmups
cp agallet.zip _vertshmups
cp batrider.zip _vertshmups
cp batsugunsp.zip _vertshmups
cp batsugun.zip _vertshmups
cp bbakraid.zip _vertshmups
cp bgaregga.zip _vertshmups
cp blswhstl.zip _vertshmups
cp brvblade.zip _vertshmups
cp cosmogng.zip _vertshmups
cp cybattlr.zip _vertshmups
cp cyvern.zip _vertshmups
cp desertwr.zip _vertshmups
cp dimahoo.zip _vertshmups
cp ddonpach.zip _vertshmups
cp ddpdoj.zip _vertshmups
cp ddp2.zip _vertshmups
cp pgm.zip _vertshmups
cp dogyuun.zip _vertshmups
cp dragnblz.zip _vertshmups
cp dspirit.zip _vertshmups
cp esprade.zip _vertshmups
cp espgal.zip _vertshmups
cp espgal2.zip _vertshmups
cp feversos.zip _vertshmups
cp fstarfrc.zip _vertshmups
cp fshark.zip _vertshmups
cp galaga.zip _vertshmups
cp galaga88.zip _vertshmups
cp gemini.zip _vertshmups
cp gunfront.zip _vertshmups
cp gunbird.zip _vertshmups
cp gunbird2.zip _vertshmups
cp gunlock.zip _vertshmups
cp guwange.zip _vertshmups
cp gyruss.zip _vertshmups
cp ibarablk.zip _vertshmups
cp ket.zip _vertshmups
cp lwings.zip _vertshmups
cp lethalth.zip _vertshmups
cp macrossp.zip _vertshmups
cp mazinger.zip _vertshmups
cp mooncrst.zip _vertshmups
cp mmpork.zip _vertshmups
cp mushisam.zip _vertshmups
cp futaribl.zip _vertshmups
cp nost.zip _vertshmups
cp phelios.zip _vertshmups
cp pinkswts.zip _vertshmups
cp plusalph.zip _vertshmups
cp raiden.zip _vertshmups
cp rdft2.zip _vertshmups
cp rfjet.zip _vertshmups
cp raiden2.zip _vertshmups
cp ryujin.zip _vertshmups
cp samuraia.zip _vertshmups
cp shienryu.zip _vertshmups
cp stvbios.zip _vertshmups
cp sstriker.zip _vertshmups
cp spacedx.zip _vertshmups
cp s1945ii.zip _vertshmups
cp s1945iii.zip _vertshmups
cp macross.zip _vertshmups
cp tenkomor.zip _vertshmups
cp terracre.zip _vertshmups
cp gametngk.zip _vertshmups
cp timeplt.zip _vertshmups
cp truxton.zip _vertshmups
cp twincobr.zip _vertshmups
cp tcobra2.zip _vertshmups
cp tdragon2.zip _vertshmups
cp twineagl.zip _vertshmups
cp twineag2.zip _vertshmups
cp twinhawk.zip _vertshmups
cp ultrax.zip _vertshmups
cp vasara.zip _vertshmups
cp vasara2.zip _vertshmups
cp viprp1.zip _vertshmups
cp wndrplnt.zip _vertshmups
cp xevious.zip _vertshmups
cp stmblade.zip _vertshmups
cp ssi.zip _vertshmups
cp ncv1.zip _vertshmups